### ISSUE TITLE
Зберігати контакти з іменами, адресами, номерами телефонів, email та днями народження до книги контактів

### ISSUE THREAD

**Issue by dan-bull** [RSMNYS/iBook#2]
В базовому коді вже є потрібні класи. AdressBook, Record, Field. 
Також базовий функціонал для додавання нового контакту теж існує.

1. Потрібно перевірити, що вже є зроблено і добавити упущений функціонал (Як приклад даний код не підтримує збереження адреси). Користувач може ввести декілька адрес через ;. Адреси зберігати в полі adresses класу Record.
2. Додати перевірки на user input, щоб ми зберігали коректно дані

Для перевірок створити власні винятки: Як приклад NameTooShortException. Коли ввід користувача буде неправильним ми зможемо викликати нашу помилку raise NameTooShortException(name). І відповідним чином обробляти її. Інші приклади: WrongEmailException, WrongPhoneFormatException і тому подібне.

**Comment by RSMNYS** [comment]
Програма має підтримувати multi input mode. До прикладу в нас буде команда add_contact. Користувач вводить тільки цю команду без параметрів: add_contact. Далі програма запитує ввести name. Після того як користувач ввів ім'я - запитує ввести телефон і тп. Перевірка правильності введення перевіряється на кожному етапі. Телефон та Ім'я є обов'язковими до введення. Дивитись приклад виконання в AddContactCommand

**Comment by dan-bull** [comment]
@RSMNYS  Можеш підказати тут буль ласка?

**Comment by RSMNYS** [comment]
@ivan-is подібно як ми робили в ДЗ

Користувач вводить: add-contact
Система виводить: Please provde name: 
КОристувач вводить ім'я. Перевірка імені на 5+ символів, якщо менше - видаємо помилку.
Як все гуд, система запитує телефон (перевірка телефону)
Система запитує birthday in format ("DD.MM.YYYY"), press enter to skip. Якщо текст введено, то робимо валідацію, як ні то просто пропускаємо.
далі email і тп

**Comment by RSMNYS** [comment]
> @dan-bull , не зрозуміло що таке multi input mode
> 
> @RSMNYS , задача звучить "Зберігати контакти з іменами, адресами, номерами телефонів, email та днями народження до книги контактів" тобто мені просто скопіювати сюди своє ДЗ? не зрозуміло в якому вигляді це має бути виконано це має бути один клас? два класи? одна функція? чи може є якийсь інтерфейс який я маю імплментувати?

Базовий код залитий в депо. Будь ласка, стягуй і подивись, що вже є . Multi input  mode - це те, що я описав: Користувач вводить: add-contact
Система виводить: Please provde name:
КОристувач вводить ім'я. Перевірка імені на 5+ символів, якщо менше - видаємо помилку.
Як все гуд, система запитує телефон (перевірка телефону)
Система запитує birthday in format ("DD.MM.YYYY"), press enter to skip. Якщо текст введено, то робимо валідацію, як ні то просто пропускаємо.
далі email і тп. 

Тобто система покроково запитує дані, а не так що користувач вводить: add-contact Sergij 1111111 10.01.1984

Як приклад це вже частково зроблено для add-contact.

**Comment by ivan-is** [comment]
@RSMNYS 
>>Базовий код залитий в депо. Будь ласка, стягуй і подивись, що вже є 
я подивився
не розумію що з цього робити мені? весь скоуп?
яка частина репозиторію відноситься до задачі?

**Comment by RSMNYS** [comment]
> @RSMNYS
> 
> > > Базовий код залитий в депо. Будь ласка, стягуй і подивись, що вже є
> > > я подивився
> > > не розумію що з цього робити мені? весь скоуп?
> > > яка частина репозиторію відноситься до задачі?

на основі існуючого коду зробити функціонал, про який я писав раніше. А саме: 

Користувач вводить: add-contact
Система виводить: Please provde name:
КОристувач вводить ім'я. Перевірка імені на 5+ символів, якщо менше - видаємо помилку.
Як все гуд, система запитує телефон (перевірка телефону)
Система запитує birthday in format ("DD.MM.YYYY"), press enter to skip. Якщо текст введено, то робимо валідацію, як ні то просто пропускаємо.
далі email і тп

@ivan-is Тобто твоя задача на існуючому коді вдосконалити ввід даних, додати перевірки для вводу імені, телефону, email, birthday. Знайди модуль command.py (src/commands). В ньому знайди клас AddContactCommand. І з ним працюй. Для справки, ми використали патерн "команда" в проекті (https://refactoring.guru/design-patterns/command/python/example) Розкажу про нього на дзвінку. І ще прохання відгукнутись в слек, і вибрати годину, яка тобі підходить, щоб зустрітись

**Comment by ivan-is** [comment]
@RSMNYS, я правильно зрозумів, я працюю тільки з "add-contact" ? решту команд (add-birthday, phone, ...) і відповідних класів я не імплементую ?

**Comment by RSMNYS** [comment]
За тобою увесь функціонал, щоб добавити контакт в книгу. І все, що цього стосується
