### ISSUE TITLE
Редагувати та видаляти записи з книги контактів

### ISSUE THREAD

**Issue by dan-bull** [RSMNYS/iBook#6]

**Comment by ivan-is** [comment]
@dan-bull, умови задачі незрозумілі
будь ласка, надай більше деталей та приклад використання

**Comment by RSMNYS** [comment]
@ivan-is  

Видалення:
Користувач вводить: remove-contact
Система запитує: please, provide name of contact to remove.
Користувач вводить ім'я
Користувач тисне enter 
Контакт видаляється з книги 

Користувач вводить: edit-contact
Система запитує: please, provide name of contact to edit.
Користувач вводить ім'я
Система виводить цей контакт.
Система запитує що змінити:
What would you like to edit:
1. name
2. phone
- Користувач тисне name
Система  виводить: Please input the new name for the contact
Користувач вводить нове ім'я, тисне enter. ім'я збережено 
- Користувач тисне phone: 
Система просить ввести номери телефонів через кому 
Ми перезаписуємо всі телефони для користувача

**Comment by ivan-is** [comment]
@RSMNYS , 
>> Користувач вводить: remove-contact
куди вводить? 

>> Контакт видаляється з книги
з якої книги? чи є десь приклад інтерфейсу? що на вході, що на виході, які типи

**Comment by RSMNYS** [comment]
@ivan-is так як в нас консольний помічник, то швидше за все користувач вводить команди в консоль? Будь ласка, стягни код, що є в репозиторії, і запусти його, ознайомся. 

"Контакт видаляється з книги
з якої книги? чи є десь приклад інтерфейсу? що на вході, що на виході, які типи"

мабуть-що з книги контактів? Це основне завдання, розробити книгу контактів. При старті програми створюється AddressBook, і використовується для збереження контактів
