### ISSUE TITLE
Всі дані (контакти, нотатки) повинні зберігатися на жорсткому диску у папці користувача

### ISSUE THREAD

**Issue by dan-bull** [RSMNYS/iBook#8]

**Comment by RSMNYS** [comment]
Пропоную адресну книгу і нотатки (Notes) зробити singletons, тобто в нас буде завжди один екземпляр класу : https://refactoring.guru/design-patterns/singleton/python/example. При створенні об'єкту (перший раз) зчитувати вміст з файлу (address_book.json, notes.json) та ініціалізувати всі властивості в ініт методі. Зберігання також зробити як метод в класі.

**Comment by RSMNYS** [comment]
В нас додано збереження книги контактів. 
Потрібно ще добавити збереження нотатків
